- name: Install dependencies
  package: name={{ item }} state=latest
  become: true
  with_items:
    - libgl1-mesa-dri:i386
    - libgl1:i386
    - libc6:i386
    - xdg-desktop-portal
    - xdg-desktop-portal-gtk
    - libgl1-nvidia-glvnd-glx:i386


- name: Add non-free sources
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free"
    state: present

- name: Install dependencies
  package: name={{ item }} state=latest
  become: true
  with_items:
    - steam-launcher





