---
- name: Neovim -- Install
  package: name={{ item }} state=latest
  become: true
  with_items:
    - fuse
    - libfuse2
    - git
    - python3-pip
    - ack-grep
    - neovim

- name: Neovim - Python dependecies
  pip:
    name: neovim

- name: Vim-plug -- Create autoload directory
  file: 
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload" 
    state: directory
    recurse: yes

- name: Vim-plug -- Install
  get_url: 
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim" 

- name: Neovim -- Create config directory
  file: 
    path: "{{ ansible_env.HOME }}/.config/nvim/colors"
    state: directory
    recurse: yes

- name: Neovim -- Config
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Setup Go env
  include: go.yml
  when: dev_vim_go

