---
- name: Reset Kubernetes component
  become: true
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Generate Token
  shell: kubeadm token generate
  register: kubernetes_token

- name: Init Kubernetes cluster
  become: true
  shell: kubeadm init --kubernetes-version {{ kubernetes_version }} \
                 --pod-network-cidr {{ kubernetes_pod_network_cidr }} \
                 --token {{ kubernetes_token.stdout }} \
                 --control-plane-endpoint {{ kubernetes_control_plane_endpoint }} \
                 {{ kubernetes_kubeadm_opts }} 
  register: init_cluster
