---
- name: Node Setup
  include_tasks: node.yml

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Initialize cluster
  include_tasks: init.yml
  when: kubernetes_node == "primary" and not kubeadm_ca.stat.exists

- name: Initialize cluster
  include_tasks: init.yml
  when: kubernetes_node == "primary" and not kubeadm_ca.stat.exists

- name: Create .kube directory
  file:
    name: .kube
    state: directory
    mode: 0755
  when: kubernetes_node == "primary" or kubernetes_node == "master" 

- name: Copy admin.conf to Home directory
  become: true
  copy:
    src: "{{ kubernetes_admin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true
  when: kubernetes_node == "primary" or kubernetes_node == "master" 
