---
- name: Create Kubernetes addon directory
  file:
    path: "{{ calico_dir }}"
    state: directory

- name: "Copy  YAML files"
  template:
    src: "calico-{{ calico_version }}.j2"
    dest: "{{ calico_dir }}/calico.yml"
  
- name: "Create  network daemonset"
  command: kubectl apply  -f {{ calico_dir }}/

- name: Install helm chart
  helm:
    host: localhost
    chart:
      name: memcached
      version: 0.4.0
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    state: present
    name: my-memcached
    namespace: default

